language: r
dist: xenial
cache: packages
branches:
    only:
        - master
r_packages:
    - tidyverse
    - qgam

>>>>>>> 367d0fac0145e7246eeb6f59b26e191b007cfe21
r_github_packages:
    - rstudio/blogdown

before_script:
    - Rscript -e 'blogdown::install_hugo()'

script:
    - Rscript -e 'blogdown::build_site()'

before_deploy:
    - rm public/.gitignore

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_PAT
    on:
        branch: master
    local_dir: public
    target_branch: gh-pages
